// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcWqoenuqniln7m8WSzbmGz_vmemy453U',
    appId: '1:929374746267:web:ab322f359ed80dd05b383e',
    messagingSenderId: '929374746267',
    projectId: 'nexus-app-f74ad',
    authDomain: 'nexus-app-f74ad.firebaseapp.com',
    storageBucket: 'nexus-app-f74ad.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK94fI2W34M5-zuQEdpBupmzyskSswz2Q',
    appId: '1:929374746267:android:c4413b44f285f7ca5b383e',
    messagingSenderId: '929374746267',
    projectId: 'nexus-app-f74ad',
    storageBucket: 'nexus-app-f74ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkWJMclNPWhFqhkvl4DEXrwciFWsREQH0',
    appId: '1:929374746267:ios:fb5fdb6ba5a794035b383e',
    messagingSenderId: '929374746267',
    projectId: 'nexus-app-f74ad',
    storageBucket: 'nexus-app-f74ad.firebasestorage.app',
    iosBundleId: 'com.nexus.app.nexusApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkWJMclNPWhFqhkvl4DEXrwciFWsREQH0',
    appId: '1:929374746267:ios:fb5fdb6ba5a794035b383e',
    messagingSenderId: '929374746267',
    projectId: 'nexus-app-f74ad',
    storageBucket: 'nexus-app-f74ad.firebasestorage.app',
    iosBundleId: 'com.nexus.app.nexusApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcWqoenuqniln7m8WSzbmGz_vmemy453U',
    appId: '1:929374746267:web:1123edcb66170dd85b383e',
    messagingSenderId: '929374746267',
    projectId: 'nexus-app-f74ad',
    authDomain: 'nexus-app-f74ad.firebaseapp.com',
    storageBucket: 'nexus-app-f74ad.firebasestorage.app',
  );
}
